<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>3 Lab 5 — October 13 | Stat 3553: Regression Modelling</title>
<meta name="author" content="Adam Shen">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="3 Lab 5 — October 13 | Stat 3553: Regression Modelling">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="3 Lab 5 — October 13 | Stat 3553: Regression Modelling">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.9/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/_IBM%20Plex%20Sans-0.4.0/font.css" rel="stylesheet">
<link href="libs/_IBM%20Plex%20Mono-0.4.0/font.css" rel="stylesheet">
<script src="libs/bs3compat-0.2.5.1/tabs.js"></script><script src="libs/bs3compat-0.2.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-148177428-3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-148177428-3');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><meta name="description" content="3.1 Packages library(tibble) library(dplyr) library(ggplot2) library(tidyr) library(broom) library(ellipse) library(palmerpenguins) theme_set(theme_bw()) The tidyr package is another component...">
<meta property="og:description" content="3.1 Packages library(tibble) library(dplyr) library(ggplot2) library(tidyr) library(broom) library(ellipse) library(palmerpenguins) theme_set(theme_bw()) The tidyr package is another component...">
<meta name="twitter:description" content="3.1 Packages library(tibble) library(dplyr) library(ggplot2) library(tidyr) library(broom) library(ellipse) library(palmerpenguins) theme_set(theme_bw()) The tidyr package is another component...">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Fall 2021">Stat 3553: Regression Modelling</a>:
        <small class="text-muted">Fall 2021</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Session info</a></li>
<li><a class="" href="lab-1-september-15.html"><span class="header-section-number">1</span> Lab 1 — September 15</a></li>
<li><a class="" href="lab-3-september-29.html"><span class="header-section-number">2</span> Lab 3 — September 29</a></li>
<li><a class="active" href="lab-5-october-13.html"><span class="header-section-number">3</span> Lab 5 — October 13</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/adamoshen/3553f21">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="lab-5-october-13" class="section level1" number="3">
<h1>
<span class="header-section-number">3</span> Lab 5 — October 13<a class="anchor" aria-label="anchor" href="#lab-5-october-13"><i class="fas fa-link"></i></a>
</h1>
<div id="packages" class="section level2" number="3.1">
<h2>
<span class="header-section-number">3.1</span> Packages<a class="anchor" aria-label="anchor" href="#packages"><i class="fas fa-link"></i></a>
</h2>
<div class="sourceCode" id="cb121"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tibble.tidyverse.org/">tibble</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org">tidyr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">ellipse</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://allisonhorst.github.io/palmerpenguins/">palmerpenguins</a></span><span class="op">)</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme_get.html">theme_set</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>The <a href="https://tidyr.tidyverse.org/">tidyr</a> package is another component package of the
<a href="https://www.tidyverse.org/packages/">tidyverse</a> that contains functions for cleaning up and
reshaping data.</p>
<p>The <code>penguins</code> data set from the <a href="https://allisonhorst.github.io/palmerpenguins/">palmerpenguins</a>
package will be used for some practice with multiple linear regression.</p>
<p>We will be using the package <a href="https://CRAN.R-project.org/package=ellipse">ellipse</a>. This package
contains functions for drawing confidence regions associated to the estimates obtained from linear
regression. Unlike the code provided in class for drawing confidence regions which took in raw data
as input, the <code><a href="https://rdrr.io/pkg/ellipse/man/ellipse.lm.html">ellipse::ellipse.lm()</a></code> function will allow you to pass in your linear model object
instead. In using the <a href="https://CRAN.R-project.org/package=ellipse">ellipse</a> package, we will however
need to draw the lines for the component confidence intervals ourselves (though this is not
difficult to do).</p>
</div>
<div id="the-pipe" class="section level2" number="3.2">
<h2>
<span class="header-section-number">3.2</span> The pipe<a class="anchor" aria-label="anchor" href="#the-pipe"><i class="fas fa-link"></i></a>
</h2>
<p>The pipe operator, <code><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></code>, can be found in the package <a href="https://magrittr.tidyverse.org/">magrittr</a>,
which should have been installed when you installed the <a href="https://dplyr.tidyverse.org/">dplyr</a>
package. When <a href="https://dplyr.tidyverse.org/">dplyr</a> is loaded (by calling <code><a href="https://dplyr.tidyverse.org">library(dplyr)</a></code>),
the <a href="https://magrittr.tidyverse.org/">magrittr</a> pipe is also imported.</p>
<p>The pipe works by taking the result on the left and passing it to the <strong>first</strong> argument of the
function on the right. The pipe allows you to write cleaner code by converting something like this:</p>
<div class="sourceCode" id="cb122"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">mydata</span>, <span class="va">var1</span> <span class="op">&gt;</span> <span class="fl">5</span><span class="op">)</span>, <span class="va">var2</span>, <span class="va">var3</span><span class="op">)</span>, var4 <span class="op">=</span> <span class="va">var2</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">var3</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>into this:</p>
<div class="sourceCode" id="cb123"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mydata</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">var1</span> <span class="op">&gt;</span> <span class="fl">5</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">var2</span>, <span class="va">var3</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>var4 <span class="op">=</span> <span class="va">var2</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">var3</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>revealing the underlying sequential logic of your workflow. Since the pipe works by taking the
result on the left and passing it to the <strong>first</strong> argument of the function on the right, the use of
the pipe when wrangling data with <a href="https://dplyr.tidyverse.org/">dplyr</a> is especially convenient as
all <a href="https://dplyr.tidyverse.org/">dplyr</a> data wrangling functions have the data frame argument as
its <strong>first</strong> argument, and in most cases, will return a data frame.</p>
<p>In the example above, the first argument to <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>, and <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> is a data frame.
After evaluation, each function also returns a data frame. Notice that as a result of piping a data
frame into each of these functions, we don't need to actually specify where it's going (since it
goes to the first argument by default) and we don't need to create extra variables for intermediate
steps.</p>
</div>
<div id="multiple-linear-regression-example-1" class="section level2" number="3.3">
<h2>
<span class="header-section-number">3.3</span> Multiple linear regression — example 1<a class="anchor" aria-label="anchor" href="#multiple-linear-regression-example-1"><i class="fas fa-link"></i></a>
</h2>
<div id="the-penguins-data" class="section level3" number="3.3.1">
<h3>
<span class="header-section-number">3.3.1</span> The penguins data<a class="anchor" aria-label="anchor" href="#the-penguins-data"><i class="fas fa-link"></i></a>
</h3>
<p>Let us load the <code>penguins</code> data set. Some of the variables that we are interested in working with
contain missing values. Immediately after loading the data, we can pass it into the <code><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na()</a></code>
function (from <a href="https://tidyr.tidyverse.org/">tidyr</a>) which will drop all rows (observations) that
contain missing values.</p>
<div class="sourceCode" id="cb124"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">penguins</span> <span class="op">&lt;-</span> <span class="fu">palmerpenguins</span><span class="fu">::</span><span class="va"><a href="https://allisonhorst.github.io/palmerpenguins/reference/penguins.html">penguins</a></span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">penguins</span><span class="op">)</span></code></pre></div>
<pre class="fansi fansi-output"><code>## <span style="color: #555555;"># A tibble: 6 x 8</span><span>
##   species island bill_length_mm bill_depth_mm flipper_length_~ body_mass_g sex  
##   </span><span style="color: #555555;font-style: italic;">&lt;fct&gt;</span><span>   </span><span style="color: #555555;font-style: italic;">&lt;fct&gt;</span><span>           </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>         </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>            </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span>       </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;fct&gt;</span><span>
## </span><span style="color: #555555;">1</span><span> Adelie  Torge~           39.1          18.7              181        </span><span style="text-decoration: underline;">3</span><span>750 male 
## </span><span style="color: #555555;">2</span><span> Adelie  Torge~           39.5          17.4              186        </span><span style="text-decoration: underline;">3</span><span>800 fema~
## </span><span style="color: #555555;">3</span><span> Adelie  Torge~           40.3          18                195        </span><span style="text-decoration: underline;">3</span><span>250 fema~
## </span><span style="color: #555555;">4</span><span> Adelie  Torge~           36.7          19.3              193        </span><span style="text-decoration: underline;">3</span><span>450 fema~
## </span><span style="color: #555555;">5</span><span> Adelie  Torge~           39.3          20.6              190        </span><span style="text-decoration: underline;">3</span><span>650 male 
## </span><span style="color: #555555;">6</span><span> Adelie  Torge~           38.9          17.8              181        </span><span style="text-decoration: underline;">3</span><span>625 fema~
## </span><span style="color: #555555;"># ... with 1 more variable: year &lt;int&gt;</span><span>
</span></code></pre>
</div>
<div id="subsetting-the-data" class="section level3" number="3.3.2">
<h3>
<span class="header-section-number">3.3.2</span> Subsetting the data<a class="anchor" aria-label="anchor" href="#subsetting-the-data"><i class="fas fa-link"></i></a>
</h3>
<p>This data set contains penguins from three species across three islands:</p>
<div class="sourceCode" id="cb125"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">penguins</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="va">species</span>, <span class="va">island</span><span class="op">)</span></code></pre></div>
<pre class="fansi fansi-output"><code>## <span style="color: #555555;"># A tibble: 5 x 2</span><span>
##   species   island   
##   </span><span style="color: #555555;font-style: italic;">&lt;fct&gt;</span><span>     </span><span style="color: #555555;font-style: italic;">&lt;fct&gt;</span><span>    
## </span><span style="color: #555555;">1</span><span> Adelie    Torgersen
## </span><span style="color: #555555;">2</span><span> Adelie    Biscoe   
## </span><span style="color: #555555;">3</span><span> Adelie    Dream    
## </span><span style="color: #555555;">4</span><span> Gentoo    Biscoe   
## </span><span style="color: #555555;">5</span><span> Chinstrap Dream
</span></code></pre>
<p>For the following example, let us focus only on the penguins of species <em>Adelie</em> from the island
<em>Biscoe</em>. We can obtain this subset of the <code>penguins</code> data using the following code:</p>
<div class="sourceCode" id="cb126"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">adeliebiscoe</span> <span class="op">&lt;-</span> <span class="va">penguins</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">species</span> <span class="op">==</span> <span class="st">"Adelie"</span>, <span class="va">island</span> <span class="op">==</span> <span class="st">"Biscoe"</span><span class="op">)</span></code></pre></div>
<p><em>(Note that in the code above, we are using two equal signs since we are making a comparison and
not setting values).</em></p>
</div>
<div id="visual-check-for-linear-relationship" class="section level3" number="3.3.3">
<h3>
<span class="header-section-number">3.3.3</span> Visual check for linear relationship<a class="anchor" aria-label="anchor" href="#visual-check-for-linear-relationship"><i class="fas fa-link"></i></a>
</h3>
<p>Suppose we are interested in fitting a model using body mass as the response and bill length, bill
depth, and flipper length as the predictors. Before building the model, we can verify that there is
a linear relationship between the response and the individual predictors.</p>
<div class="sourceCode" id="cb127"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">adeliebiscoe</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">bill_length_mm</span>, y<span class="op">=</span><span class="va">body_mass_g</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="03_files/figure-html/unnamed-chunk-8-1.svg" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb128"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">adeliebiscoe</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">bill_depth_mm</span>, y<span class="op">=</span><span class="va">body_mass_g</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="03_files/figure-html/unnamed-chunk-9-1.svg" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb129"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">adeliebiscoe</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">flipper_length_mm</span>, y<span class="op">=</span><span class="va">body_mass_g</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="03_files/figure-html/unnamed-chunk-10-1.svg" width="672" style="display: block; margin: auto;"></div>
<p>The plots look <em>okay</em>... Let's go ahead and fit the model.</p>
</div>
<div id="fit-the-model" class="section level3" number="3.3.4">
<h3>
<span class="header-section-number">3.3.4</span> Fit the model<a class="anchor" aria-label="anchor" href="#fit-the-model"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb130"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">adeliebiscoe_lm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">bill_length_mm</span> <span class="op">+</span> <span class="va">bill_depth_mm</span> <span class="op">+</span> <span class="va">flipper_length_mm</span>, data<span class="op">=</span><span class="va">adeliebiscoe</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">adeliebiscoe_lm</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = body_mass_g ~ bill_length_mm + bill_depth_mm + flipper_length_mm, 
##     data = adeliebiscoe)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -836.50 -186.29   19.01  183.14  486.90 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -6122.000   1341.697  -4.563 4.71e-05 ***
## bill_length_mm       70.743     21.445   3.299 0.002046 ** 
## bill_depth_mm       165.196     43.802   3.771 0.000526 ***
## flipper_length_mm    21.397      7.262   2.947 0.005336 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 298.8 on 40 degrees of freedom
## Multiple R-squared:  0.6508, Adjusted R-squared:  0.6246 
## F-statistic: 24.85 on 3 and 40 DF,  p-value: 3.048e-09</code></pre>
<p>From the above output, the equation of our fitted line is:</p>
<p><span class="math display">\[\widehat{y}_{i} \,=\, -6122 \,+\, 70.743x_{1} \,+\, 165.196x_{2} + 21.397x_{3}\]</span></p>
<p>where:</p>
<ul>
<li>
<span class="math inline">\(\widehat{y}_{i}\)</span> is the predicted body mass</li>
<li>
<span class="math inline">\(x_{1}\)</span> is the bill length</li>
<li>
<span class="math inline">\(x_{2}\)</span> is the bill depth</li>
<li>
<span class="math inline">\(x_{3}\)</span> is the flipper length</li>
</ul>
</div>
<div id="fit-a-model-without-an-intercept" class="section level3" number="3.3.5">
<h3>
<span class="header-section-number">3.3.5</span> Fit a model without an intercept<a class="anchor" aria-label="anchor" href="#fit-a-model-without-an-intercept"><i class="fas fa-link"></i></a>
</h3>
<p>By default, linear models are fitted with an intercept. We can fit a linear model without an
intercept by adding a <code>+ 0</code> or a <code>- 1</code> in the formula specification (see the Details section of
<code><a href="https://rdrr.io/r/stats/lm.html">?lm</a></code>). To make the hypothesis tests that we will do in the next section a bit more interesting,
let us remove the intercept from the model that we just fit.</p>
<p>As shown in Lab 1, we can do this by fitting a brand new model:</p>
<div class="sourceCode" id="cb132"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">adeliebiscoe_lm0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">bill_length_mm</span> <span class="op">+</span> <span class="va">bill_depth_mm</span> <span class="op">+</span> <span class="va">flipper_length_mm</span> <span class="op">-</span> <span class="fl">1</span>, data<span class="op">=</span><span class="va">adeliebiscoe</span><span class="op">)</span></code></pre></div>
<p>or by using <code><a href="https://rdrr.io/r/stats/update.html">update()</a></code>:</p>
<div class="sourceCode" id="cb133"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">adeliebiscoe_lm0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">adeliebiscoe_lm</span>, formula <span class="op">=</span> <span class="va">.</span> <span class="op">~</span> <span class="va">.</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span></code></pre></div>
<p>Recall that the above line of code means that <code>adeliebiscoe_lm0</code> is constructed by taking the
existing <code>adeliebiscoe_lm</code> and updating its formula. The response variable remains the same
(represented by the dot on the left of the tilde), the predictors remain the same (represented by
the dot on the right of the tilde) and a <code>- 1</code> denotes that we do not want an intercept.</p>
<p>Let's take a look at our new model.</p>
<div class="sourceCode" id="cb134"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">adeliebiscoe_lm0</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = body_mass_g ~ bill_length_mm + bill_depth_mm + flipper_length_mm - 
##     1, data = adeliebiscoe)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -737.69 -296.78   41.82  236.37  769.39 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)  
## bill_length_mm      58.741     25.922   2.266   0.0288 *
## bill_depth_mm      125.323     52.276   2.397   0.0212 *
## flipper_length_mm   -4.635      5.471  -0.847   0.4018  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 363.9 on 41 degrees of freedom
## Multiple R-squared:  0.9912, Adjusted R-squared:  0.9905 
## F-statistic:  1536 on 3 and 41 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Interestingly, by removing the intercept from the model, our adjusted R-squared value went from
0.6246 to 0.9905 👀.</p>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="lab-3-september-29.html"><span class="header-section-number">2</span> Lab 3 — September 29</a></div>
<div class="empty"></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#lab-5-october-13"><span class="header-section-number">3</span> Lab 5 — October 13</a></li>
<li><a class="nav-link" href="#packages"><span class="header-section-number">3.1</span> Packages</a></li>
<li><a class="nav-link" href="#the-pipe"><span class="header-section-number">3.2</span> The pipe</a></li>
<li>
<a class="nav-link" href="#multiple-linear-regression-example-1"><span class="header-section-number">3.3</span> Multiple linear regression — example 1</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#the-penguins-data"><span class="header-section-number">3.3.1</span> The penguins data</a></li>
<li><a class="nav-link" href="#subsetting-the-data"><span class="header-section-number">3.3.2</span> Subsetting the data</a></li>
<li><a class="nav-link" href="#visual-check-for-linear-relationship"><span class="header-section-number">3.3.3</span> Visual check for linear relationship</a></li>
<li><a class="nav-link" href="#fit-the-model"><span class="header-section-number">3.3.4</span> Fit the model</a></li>
<li><a class="nav-link" href="#fit-a-model-without-an-intercept"><span class="header-section-number">3.3.5</span> Fit a model without an intercept</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/adamoshen/3553f21/blob/main/03.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/adamoshen/3553f21/edit/main/03.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Stat 3553: Regression Modelling</strong>: Fall 2021" was written by Adam Shen. It was last built on October 13, 2021.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
