<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>4 Lab 7 — November 10 | Stat 3553: Regression Modelling</title>
<meta name="author" content="Adam Shen">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="4 Lab 7 — November 10 | Stat 3553: Regression Modelling">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="4 Lab 7 — November 10 | Stat 3553: Regression Modelling">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.9/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/_IBM%20Plex%20Sans-0.4.0/font.css" rel="stylesheet">
<link href="libs/_IBM%20Plex%20Mono-0.4.0/font.css" rel="stylesheet">
<script src="libs/bs3compat-0.2.5.1/tabs.js"></script><script src="libs/bs3compat-0.2.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-148177428-3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-148177428-3');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><meta name="description" content="4.1 Packages library(tibble) library(dplyr) library(ggplot2) library(tidyr) library(readr) library(broom) library(leaps) theme_set(theme_bw()) readr is another package from tidyverse for reading...">
<meta property="og:description" content="4.1 Packages library(tibble) library(dplyr) library(ggplot2) library(tidyr) library(readr) library(broom) library(leaps) theme_set(theme_bw()) readr is another package from tidyverse for reading...">
<meta name="twitter:description" content="4.1 Packages library(tibble) library(dplyr) library(ggplot2) library(tidyr) library(readr) library(broom) library(leaps) theme_set(theme_bw()) readr is another package from tidyverse for reading...">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Fall 2021">Stat 3553: Regression Modelling</a>:
        <small class="text-muted">Fall 2021</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Session info</a></li>
<li><a class="" href="lab-1-september-15.html"><span class="header-section-number">1</span> Lab 1 — September 15</a></li>
<li><a class="" href="lab-3-september-29.html"><span class="header-section-number">2</span> Lab 3 — September 29</a></li>
<li><a class="" href="lab-5-october-13.html"><span class="header-section-number">3</span> Lab 5 — October 13</a></li>
<li><a class="active" href="lab-7-november-10.html"><span class="header-section-number">4</span> Lab 7 — November 10</a></li>
<li><a class="" href="lab-9-december-1.html"><span class="header-section-number">5</span> Lab 9 — December 1</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/adamoshen/3553f21">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="lab-7-november-10" class="section level1" number="4">
<h1>
<span class="header-section-number">4</span> Lab 7 — November 10<a class="anchor" aria-label="anchor" href="#lab-7-november-10"><i class="fas fa-link"></i></a>
</h1>
<div id="packages-1" class="section level2" number="4.1">
<h2>
<span class="header-section-number">4.1</span> Packages<a class="anchor" aria-label="anchor" href="#packages-1"><i class="fas fa-link"></i></a>
</h2>
<div class="sourceCode" id="cb217"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tibble.tidyverse.org/">tibble</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org">tidyr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://readr.tidyverse.org">readr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">leaps</span><span class="op">)</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme_get.html">theme_set</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><a href="https://readr.tidyverse.org/">readr</a> is another package from
<a href="https://tidyverse.org/packages">tidyverse</a> for reading in various types of data. Many of its
functions work similar to the base-R equivalents but work a bit better, are smarter, and read data
in as a tibble.</p>
<p>We will be using the <a href="https://cran.r-project.org/package=leaps">leaps</a> package to aid us in
computing all possible models from a set of predictors and obtaining the corresponding Mallows'
<span class="math inline">\(C_{p}\)</span> values for all of these models. The <a href="https://cran.r-project.org/package=leaps">leaps</a>
package can also be used for best subset selection, forward selection, and backward selection. In
this lab, while we will be covering an example on backward selection, we will be doing it manually
to throroughly illustrate the process.</p>
</div>
<div id="weighted-linear-regression-via-lm" class="section level2" number="4.2">
<h2>
<span class="header-section-number">4.2</span> Weighted linear regression (via <code>lm</code>)<a class="anchor" aria-label="anchor" href="#weighted-linear-regression-via-lm"><i class="fas fa-link"></i></a>
</h2>
<p>Last time, we saw how to compute the weighted least squares estimates for <span class="math inline">\(\beta\)</span> using matrices.
Now, let's take a look at how to do it via the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function. The data we will use for this
example is the data from Table 2.1 (page 51).</p>
<p>I entered the data manually myself, so let's double-check that my values are correct. The resulting
regression equation should be <span class="math inline">\(\widehat{Y}_{i} = 1.426 + 0.316X_{i}\)</span> (page 51).</p>
<div class="sourceCode" id="cb218"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">table2.1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span><span class="op">(</span><span class="st">"./data/table2.1_DS.txt"</span>, header<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X</span>, data<span class="op">=</span><span class="va">table2.1</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## (Intercept)           X 
##   1.4256449   0.3157857</code></pre>
<p>Looks good!</p>
<div id="problem-i" class="section level3" number="4.2.1">
<h3>
<span class="header-section-number">4.2.1</span> Problem (i)<a class="anchor" aria-label="anchor" href="#problem-i"><i class="fas fa-link"></i></a>
</h3>
<p>Suppose we are told that the 16th observation has variance <span class="math inline">\(16\sigma^{2}\)</span> rather than <span class="math inline">\(\sigma^{2}\)</span>.
Obtain the parameter estimates using weighted least squares.</p>
</div>
<div id="solution" class="section level3" number="4.2.2">
<h3>
<span class="header-section-number">4.2.2</span> Solution<a class="anchor" aria-label="anchor" href="#solution"><i class="fas fa-link"></i></a>
</h3>
<p>If the 16th observation has variance <span class="math inline">\(16\sigma^{2}\)</span>, then</p>
<p><span class="math display">\[\textbf{Var}(\varepsilon) \,=\, \sigma^{2}V \,=\,
\sigma^{2}\begin{bmatrix}1\\
&amp;1\\
&amp; &amp;\ddots\\
&amp; &amp; &amp;16\\
&amp; &amp; &amp; &amp;\ddots\\
&amp; &amp; &amp; &amp; &amp;1\\
&amp; &amp; &amp; &amp; &amp; &amp;1
\end{bmatrix}\]</span></p>
<p>The weight matrix, <span class="math inline">\(V^{-1}\)</span>, is calculated as the inverse of <span class="math inline">\(V\)</span>. We know that the inverse of
a diagonal matrix is the same matrix but with the diagonal elements reciprocated. Thus we have</p>
<p><span class="math display">\[V^{-1} \,=\,
\begin{bmatrix}1\\
&amp;1\\
&amp; &amp;\ddots\\
&amp; &amp; &amp;1/16\\
&amp; &amp; &amp; &amp;\ddots\\
&amp; &amp; &amp; &amp; &amp;1\\
&amp; &amp; &amp; &amp; &amp; &amp;1
\end{bmatrix}\]</span></p>
<p>The weights we will supply to <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> will be a vector of 15 ones, followed by the value <span class="math inline">\(1/16\)</span>,
followed by 7 ones. Instead of typing the number <code>1</code> 15 times, we can use the <code><a href="https://rdrr.io/r/base/rep.html">rep()</a></code> function
which repeats a value <span class="math inline">\(n\)</span> times.</p>
<div class="sourceCode" id="cb220"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">w1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">15</span><span class="op">)</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">16</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">7</span><span class="op">)</span><span class="op">)</span>
<span class="va">w1</span></code></pre></div>
<pre><code>##  [1] 1.0000 1.0000 1.0000 1.0000 1.0000 1.0000 1.0000 1.0000 1.0000 1.0000
## [11] 1.0000 1.0000 1.0000 1.0000 1.0000 0.0625 1.0000 1.0000 1.0000 1.0000
## [21] 1.0000 1.0000 1.0000</code></pre>
<div class="sourceCode" id="cb222"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Check that it has the same length as the data (n=23)</span>
<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">w1</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 23</code></pre>
<div class="sourceCode" id="cb224"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Check that the value at position 16 is correct</span>
<span class="va">w1</span><span class="op">[</span><span class="fl">16</span><span class="op">]</span></code></pre></div>
<pre><code>## [1] 0.0625</code></pre>
<p>Now we can proceed with building the model.</p>
<div class="sourceCode" id="cb226"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">wm1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X</span>, data<span class="op">=</span><span class="va">table2.1</span>, weights<span class="op">=</span><span class="va">w1</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">wm1</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ X, data = table2.1, weights = w1)
## 
## Weighted Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.18059 -0.51519 -0.07287  0.25786  2.39631 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)   1.4421     0.5112   2.821   0.0102 *
## X             0.3077     0.1155   2.663   0.0145 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.8485 on 21 degrees of freedom
## Multiple R-squared:  0.2525, Adjusted R-squared:  0.2169 
## F-statistic: 7.094 on 1 and 21 DF,  p-value: 0.01454</code></pre>
<p>The equation of the fitted line is:</p>
<p><span class="math display">\[\widehat{Y}_{i} \,=\, 1.4421 \,+\, 0.3077X_{i}\]</span></p>
</div>
<div id="problem-ii" class="section level3" number="4.2.3">
<h3>
<span class="header-section-number">4.2.3</span> Problem (ii)<a class="anchor" aria-label="anchor" href="#problem-ii"><i class="fas fa-link"></i></a>
</h3>
<p>Suppose we are now told that the 16th observation has variance <span class="math inline">\(25\sigma^{2}\)</span> rather than
<span class="math inline">\(\sigma^{2}\)</span>. Obtain the parameter estimates using weighted least squares.</p>
</div>
<div id="solution-1" class="section level3" number="4.2.4">
<h3>
<span class="header-section-number">4.2.4</span> Solution<a class="anchor" aria-label="anchor" href="#solution-1"><i class="fas fa-link"></i></a>
</h3>
<p>We repeat the process from before. Since the variance for the 16th observation has been scaled by
a factor of 25, the weight will be <span class="math inline">\(1/25\)</span>.</p>
<div class="sourceCode" id="cb228"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">w2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">15</span><span class="op">)</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">25</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">7</span><span class="op">)</span><span class="op">)</span>
<span class="va">w2</span></code></pre></div>
<pre><code>##  [1] 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00
## [16] 0.04 1.00 1.00 1.00 1.00 1.00 1.00 1.00</code></pre>
<div class="sourceCode" id="cb230"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Check that it has the same length as the data (n=23)</span>
<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">w2</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 23</code></pre>
<div class="sourceCode" id="cb232"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Check that the value at position 16 is correct</span>
<span class="va">w2</span><span class="op">[</span><span class="fl">16</span><span class="op">]</span></code></pre></div>
<pre><code>## [1] 0.04</code></pre>
<p>Building a second model,</p>
<div class="sourceCode" id="cb234"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">wm2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X</span>, data<span class="op">=</span><span class="va">table2.1</span>, weights<span class="op">=</span><span class="va">w2</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">wm2</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ X, data = table2.1, weights = w2)
## 
## Weighted Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.17998 -0.51499 -0.07274  0.25852  2.39727 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)   1.4425     0.5112   2.822   0.0102 *
## X             0.3075     0.1155   2.661   0.0146 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.8483 on 21 degrees of freedom
## Multiple R-squared:  0.2522, Adjusted R-squared:  0.2166 
## F-statistic: 7.082 on 1 and 21 DF,  p-value: 0.01461</code></pre>
<p>The equation of the fitted line is:</p>
<p><span class="math display">\[\widehat{Y}_{i} \,=\, 1.4425 \,+\, 0.3075X_{i}\]</span></p>
<p>We can see that in changing our weight for the 16th observation from <span class="math inline">\(1/16\)</span> to <span class="math inline">\(1/25\)</span>:</p>
<ul>
<li>The value of <span class="math inline">\(\widehat{\beta}_{0}\)</span> has increased (not by much)</li>
<li>The value of <span class="math inline">\(\widehat{\beta}_{1}\)</span> has decreased (not by much)</li>
</ul>
<p>The differences are more apparent when adjusting weights to the 23rd observation of this data set.
Hint: make a scatterplot!</p>
<p>First, let's add a column of indices to the data.</p>
<div class="sourceCode" id="cb236"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">table2.1</span> <span class="op">&lt;-</span> <span class="va">table2.1</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>obs <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>, .before <span class="op">=</span> <span class="fu"><a href="https://tidyselect.r-lib.org/reference/everything.html">everything</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span>

<span class="va">table2.1</span></code></pre></div>
<pre class="fansi fansi-output"><code>## <span style="color: #555555;"># A tibble: 23 x 3</span><span>
##      obs     Y     X
##    </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>
## </span><span style="color: #555555;"> 1</span><span>     1   2.3   1.3
## </span><span style="color: #555555;"> 2</span><span>     2   1.8   1.3
## </span><span style="color: #555555;"> 3</span><span>     3   2.8   2  
## </span><span style="color: #555555;"> 4</span><span>     4   1.5   2  
## </span><span style="color: #555555;"> 5</span><span>     5   2.2   2.7
## </span><span style="color: #555555;"> 6</span><span>     6   3.8   3.3
## </span><span style="color: #555555;"> 7</span><span>     7   1.8   3.3
## </span><span style="color: #555555;"> 8</span><span>     8   3.7   3.7
## </span><span style="color: #555555;"> 9</span><span>     9   1.7   3.7
## </span><span style="color: #555555;">10</span><span>    10   2.8   4  
## </span><span style="color: #555555;"># ... with 13 more rows</span><span>
</span></code></pre>
<p>Then we can make a scatterplot and label each point with its observation number.</p>
<div class="sourceCode" id="cb237"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">table2.1</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">X</span>, y<span class="op">=</span><span class="va">Y</span>, label<span class="op">=</span><span class="va">obs</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha<span class="op">=</span><span class="fl">0.4</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_text.html">geom_text</a></span><span class="op">(</span>hjust<span class="op">=</span><span class="st">"outward"</span>, vjust<span class="op">=</span><span class="st">"outward"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="04_files/figure-html/unnamed-chunk-9-1.svg" width="672" style="display: block; margin: auto;"></div>
<p>Observation 23 definitely stands out from the rest of the data!</p>
</div>
</div>
<div id="all-possible-models" class="section level2" number="4.3">
<h2>
<span class="header-section-number">4.3</span> All possible models<a class="anchor" aria-label="anchor" href="#all-possible-models"><i class="fas fa-link"></i></a>
</h2>
<p>To be consistent with the textbook, let us define <span class="math inline">\(p\)</span> as the total number of parameters in a model,
including the intercept. Suppose we are interested in plotting Mallows' <span class="math inline">\(C_{p}\)</span> against <span class="math inline">\(p\)</span> for
all possible models.</p>
<p><em>(Alternatively, we could consider plotting <span class="math inline">\(C_{p}\)</span> against <span class="math inline">\(p+1\)</span> where <span class="math inline">\(p\)</span> is the number of
non-intercept parameters).</em></p>
<p>Returning to the <code>rock</code> data set, an outline of our plan will be as follows:</p>
<ol style="list-style-type: decimal">
<li><p>To compute all the possible models in a single line, we employ <code><a href="https://rdrr.io/pkg/leaps/man/regsubsets.html">leaps::regsubsets()</a></code>. In the
formula argument (<code>x</code>), we specify the formula <code>area ~ .</code>. This means fix <code>area</code> as the response
variable, and allow <em>any</em> other variables appearing in the data set to be added to the candidate
model (this is so that we don't need to manually type the names of the variables in our data set).
We also set <code>nbest=3</code> to force computation of <strong>all</strong> models when <span class="math inline">\(p &lt; 4\)</span>.</p></li>
<li><p>We then pass the result through a custom function that is derived from <code><a href="https://broom.tidymodels.org/reference/tidy.regsubsets.html">broom::tidy.regsubsets()</a></code>
to obtain the required diagnostic information (including Mallows' <span class="math inline">\(C_{p}\)</span>) as a tidy tibble. We need
a custom function since we also want the <span class="math inline">\(SSE_{p}\)</span> of each model in order to calculate the <span class="math inline">\(MSE_{p}\)</span>
(or equivalently, the <span class="math inline">\(S^{2}_{p}\)</span>).</p></li>
<li><p>We can then create the column, <span class="math inline">\(p\)</span>, that counts the number of predictors included in the model
(including the intercept). This involves some code that is a bit more complicated, but it is
essentially summing the number of <code>TRUE</code>s appearing in each row (i.e. we are performing a
horizontal sum rather than the usual vertical sum).</p></li>
<li><p>We then compute the mean square error, <span class="math inline">\(S^{2}_{p}\)</span>, for each model.</p></li>
<li><p>We then drop the columns that we won't be using.</p></li>
<li><p>Finally, we can plot our results.</p></li>
</ol>
<div id="a-custom-tidy-function" class="section level3" number="4.3.1">
<h3>
<span class="header-section-number">4.3.1</span> A custom tidy function<a class="anchor" aria-label="anchor" href="#a-custom-tidy-function"><i class="fas fa-link"></i></a>
</h3>
<p>We can access the source code used to tidy objects of class <code>regsubsets</code> by calling
<code>broom:::tidy.regsubsets</code> (three colons).</p>
<div class="sourceCode" id="cb238"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">broom</span><span class="fu">:::</span><span class="va"><a href="https://broom.tidymodels.org/reference/tidy.regsubsets.html">tidy.regsubsets</a></span></code></pre></div>
<pre><code>## function (x, ...) 
## {
##     s &lt;- summary(x)
##     inclusions &lt;- as_tibble(s$which)
##     metrics &lt;- with(s, tibble(r.squared = rsq, adj.r.squared = adjr2, 
##         BIC = bic, mallows_cp = cp))
##     bind_cols(inclusions, metrics)
## }
## &lt;bytecode: 0x0000000030393080&gt;
## &lt;environment: namespace:broom&gt;</code></pre>
<p>Consulting the documentation of <code>?leaps::regsubsets()</code>, we can create a custom function that also
includes the SSE of each model.</p>
<div class="sourceCode" id="cb240"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tidy.regsubsets2</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span>, <span class="va">...</span><span class="op">)</span> <span class="op">{</span>
  <span class="va">s</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>
  <span class="va">inclusions</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="va">s</span><span class="op">$</span><span class="va">which</span><span class="op">)</span>
  <span class="va">metrics</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">s</span>, <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>r.squared <span class="op">=</span> <span class="va">rsq</span>, adj.r.squared <span class="op">=</span> <span class="va">adjr2</span>, 
                            BIC <span class="op">=</span> <span class="va">bic</span>, mallows_cp <span class="op">=</span> <span class="va">cp</span>, SSE_p <span class="op">=</span> <span class="va">rss</span><span class="op">)</span><span class="op">)</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind.html">bind_cols</a></span><span class="op">(</span><span class="va">inclusions</span>, <span class="va">metrics</span><span class="op">)</span>
<span class="op">}</span></code></pre></div>
</div>
<div id="getting-the-results" class="section level3" number="4.3.2">
<h3>
<span class="header-section-number">4.3.2</span> Getting the results<a class="anchor" aria-label="anchor" href="#getting-the-results"><i class="fas fa-link"></i></a>
</h3>
<p>Recall that</p>
<p><span class="math display">\[\widehat{\sigma}^{2}_{p} \,=\, S^{2}_{p} \,=\, \frac{SSE_{p}}{n-p}\]</span></p>
<p>where <span class="math inline">\(n\)</span> is the number of observations in your data, and <span class="math inline">\(p\)</span> is the number of parameters including
the intercept.</p>
<div class="sourceCode" id="cb241"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">rock</span><span class="op">)</span>

<span class="va">all_models</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/leaps/man/regsubsets.html">regsubsets</a></span><span class="op">(</span><span class="va">area</span> <span class="op">~</span> <span class="va">.</span>, data<span class="op">=</span><span class="va">rock</span>, method<span class="op">=</span><span class="st">"exhaustive"</span>, nbest<span class="op">=</span><span class="fl">3</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">tidy.regsubsets2</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rowwise.html">rowwise</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>p <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/c_across.html">c_across</a></span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.logical</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>s.squared_p <span class="op">=</span> <span class="va">SSE_p</span> <span class="op">/</span> <span class="op">(</span><span class="va">n</span> <span class="op">-</span> <span class="va">p</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">r.squared</span>, <span class="va">BIC</span>, <span class="va">SSE_p</span><span class="op">)</span><span class="op">)</span>

<span class="va">all_models</span></code></pre></div>
<pre class="fansi fansi-output"><code>## <span style="color: #555555;"># A tibble: 7 x 8</span><span>
##   `(Intercept)` peri  shape perm  adj.r.squared mallows_cp     p s.squared_p
##   </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span>         </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span>         </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>      </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span>       </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>
## </span><span style="color: #555555;">1</span><span> TRUE          TRUE  FALSE FALSE        0.669       20.8      2    2</span><span style="text-decoration: underline;">380</span><span>718.
## </span><span style="color: #555555;">2</span><span> TRUE          FALSE FALSE TRUE         0.139      125.       2    6</span><span style="text-decoration: underline;">201</span><span>808.
## </span><span style="color: #555555;">3</span><span> TRUE          FALSE TRUE  FALSE        0.012</span><span style="text-decoration: underline;">2</span><span>     150.       2    7</span><span style="text-decoration: underline;">115</span><span>420.
## </span><span style="color: #555555;">4</span><span> TRUE          TRUE  FALSE TRUE         0.764        3.20     3    1</span><span style="text-decoration: underline;">696</span><span>625.
## </span><span style="color: #555555;">5</span><span> TRUE          TRUE  TRUE  FALSE        0.701       15.4      3    2</span><span style="text-decoration: underline;">152</span><span>972.
## </span><span style="color: #555555;">6</span><span> TRUE          FALSE TRUE  TRUE         0.122      126.       3    6</span><span style="text-decoration: underline;">323</span><span>336.
## </span><span style="color: #555555;">7</span><span> TRUE          TRUE  TRUE  TRUE         0.765        4        4    1</span><span style="text-decoration: underline;">689</span><span>242.
</span></code></pre>
<p>In choosing a model, we want a model that has a high adjusted <span class="math inline">\(R^{2}\)</span>, <span class="math inline">\(C_{p} \approx p\)</span>, low
<span class="math inline">\(S^{2}_{p}\)</span>, and as few predictors as possible. From the results above, models 4 and 7 are quite
similar with model 7 (the full model) being only slightly better.</p>
</div>
<div id="obtaining-the-values-for-the-intercept-only-model" class="section level3" number="4.3.3">
<h3>
<span class="header-section-number">4.3.3</span> Obtaining the values for the intercept-only model<a class="anchor" aria-label="anchor" href="#obtaining-the-values-for-the-intercept-only-model"><i class="fas fa-link"></i></a>
</h3>
<p>We first fit the intercept-only model.</p>
<div class="sourceCode" id="cb242"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">rock_intercept_lm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">area</span> <span class="op">~</span> <span class="fl">1</span>, data<span class="op">=</span><span class="va">rock</span><span class="op">)</span></code></pre></div>
<p>The formula for Mallows' <span class="math inline">\(C_{p}\)</span> is given on page 332 of the textbook:</p>
<p><span class="math display">\[C_{p} \,=\, \frac{SSE_{p}}{S^{2}} \,-\, (n - 2p)\]</span></p>
<p>where <span class="math inline">\(S^{2}\)</span> is the estimate of the error term variance for the maximal model <span class="math inline">\((p=4)\)</span>. Note that
the value for <span class="math inline">\(n\)</span> has already been initialised as a variable in our workspace. We can extract the
value of <span class="math inline">\(S^{2}_{4}\)</span> from our previous results using:</p>
<div class="sourceCode" id="cb243"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">s.squared_4</span> <span class="op">&lt;-</span> <span class="va">all_models</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_tail</a></span><span class="op">(</span>n<span class="op">=</span><span class="fl">1</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">s.squared_p</span><span class="op">)</span></code></pre></div>
<p>We have the relationship that</p>
<p><span class="math display">\[S^{2}_{1} \,=\, MSE_{1} \,=\, \frac{SSE_{1}}{\text{df}_{1}}\]</span></p>
<p>Rearranging gives</p>
<p><span class="math display">\[SSE_{1} \,=\, \text{df}_{1} * S^{2}_{1}\]</span></p>
<p>Mimicking the structure of <code>all_models</code>, the corresponding values for our intercept-only model are:</p>
<div class="sourceCode" id="cb244"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">intercept_lm_results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>
  `(Intercept)` <span class="op">=</span> <span class="cn">TRUE</span>,
  peri <span class="op">=</span> <span class="cn">FALSE</span>,
  shape <span class="op">=</span> <span class="cn">FALSE</span>,
  perm <span class="op">=</span> <span class="cn">FALSE</span>,
  adj.r.squared <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">rock_intercept_lm</span><span class="op">)</span><span class="op">$</span><span class="va">adj.r.squared</span>,
  s.squared_p <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">rock_intercept_lm</span><span class="op">)</span><span class="op">$</span><span class="va">sigma</span><span class="op">^</span><span class="fl">2</span>,
  p <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">rock_intercept_lm</span><span class="op">)</span><span class="op">$</span><span class="va">df</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>,
  df <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">rock_intercept_lm</span><span class="op">)</span><span class="op">$</span><span class="va">df</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>,
  mallows_cp <span class="op">=</span> <span class="op">(</span><span class="va">s.squared_p</span> <span class="op">*</span> <span class="va">df</span><span class="op">)</span> <span class="op">/</span> <span class="va">s.squared_4</span> <span class="op">-</span> <span class="op">(</span><span class="va">n</span> <span class="op">-</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">p</span><span class="op">)</span>
<span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.logical</span><span class="op">)</span>, <span class="va">adj.r.squared</span>, <span class="va">mallows_cp</span>, <span class="va">p</span>, <span class="va">s.squared_p</span><span class="op">)</span>

<span class="va">intercept_lm_results</span></code></pre></div>
<pre class="fansi fansi-output"><code>## <span style="color: #555555;"># A tibble: 1 x 8</span><span>
##   `(Intercept)` peri  shape perm  adj.r.squared mallows_cp     p s.squared_p
##   </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span>         </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span>         </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>      </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span>       </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>
## </span><span style="color: #555555;">1</span><span> TRUE          FALSE FALSE FALSE             0       154.     1    7</span><span style="text-decoration: underline;">203</span><span>045.
</span></code></pre>
<p>Binding this to the main output:</p>
<div class="sourceCode" id="cb245"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">all_models</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind.html">bind_rows</a></span><span class="op">(</span><span class="va">intercept_lm_results</span>, <span class="va">all_models</span><span class="op">)</span>

<span class="va">all_models</span></code></pre></div>
<pre class="fansi fansi-output"><code>## <span style="color: #555555;"># A tibble: 8 x 8</span><span>
##   `(Intercept)` peri  shape perm  adj.r.squared mallows_cp     p s.squared_p
##   </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span>         </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span>         </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>      </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span>       </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>
## </span><span style="color: #555555;">1</span><span> TRUE          FALSE FALSE FALSE        0          154.       1    7</span><span style="text-decoration: underline;">203</span><span>045.
## </span><span style="color: #555555;">2</span><span> TRUE          TRUE  FALSE FALSE        0.669       20.8      2    2</span><span style="text-decoration: underline;">380</span><span>718.
## </span><span style="color: #555555;">3</span><span> TRUE          FALSE FALSE TRUE         0.139      125.       2    6</span><span style="text-decoration: underline;">201</span><span>808.
## </span><span style="color: #555555;">4</span><span> TRUE          FALSE TRUE  FALSE        0.012</span><span style="text-decoration: underline;">2</span><span>     150.       2    7</span><span style="text-decoration: underline;">115</span><span>420.
## </span><span style="color: #555555;">5</span><span> TRUE          TRUE  FALSE TRUE         0.764        3.20     3    1</span><span style="text-decoration: underline;">696</span><span>625.
## </span><span style="color: #555555;">6</span><span> TRUE          TRUE  TRUE  FALSE        0.701       15.4      3    2</span><span style="text-decoration: underline;">152</span><span>972.
## </span><span style="color: #555555;">7</span><span> TRUE          FALSE TRUE  TRUE         0.122      126.       3    6</span><span style="text-decoration: underline;">323</span><span>336.
## </span><span style="color: #555555;">8</span><span> TRUE          TRUE  TRUE  TRUE         0.765        4        4    1</span><span style="text-decoration: underline;">689</span><span>242.
</span></code></pre>
</div>
<div id="plotting-the-results" class="section level3" number="4.3.4">
<h3>
<span class="header-section-number">4.3.4</span> Plotting the results<a class="anchor" aria-label="anchor" href="#plotting-the-results"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb246"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">all_models</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">p</span>, y<span class="op">=</span><span class="va">mallows_cp</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>caption<span class="op">=</span><span class="st">"p is the number of parameter estimates including the intercept"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="04_files/figure-html/unnamed-chunk-17-1.svg" width="672" style="display: block; margin: auto;"></div>
</div>
</div>
<div id="stepwise-selection" class="section level2" number="4.4">
<h2>
<span class="header-section-number">4.4</span> Stepwise selection<a class="anchor" aria-label="anchor" href="#stepwise-selection"><i class="fas fa-link"></i></a>
</h2>
<p>Let's revisit the penguins data from
<a href="https://allisonhorst.github.io/palmerpenguins/">palmerpenguins</a>, specifically the subset of
penguins of species Adelie from the island Biscoe.</p>
<div class="sourceCode" id="cb247"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">adeliebiscoe</span> <span class="op">&lt;-</span> <span class="fu">palmerpenguins</span><span class="fu">::</span><span class="va"><a href="https://allisonhorst.github.io/palmerpenguins/reference/penguins.html">penguins</a></span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">species</span> <span class="op">==</span> <span class="st">"Adelie"</span>, <span class="va">island</span> <span class="op">==</span> <span class="st">"Biscoe"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>
    bill_length <span class="op">=</span> <span class="va">bill_length_mm</span>,
    bill_depth <span class="op">=</span> <span class="va">bill_depth_mm</span>,
    flipper_length <span class="op">=</span> <span class="va">flipper_length_mm</span>,
    body_mass <span class="op">=</span> <span class="va">body_mass_g</span>,
  <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">body_mass</span>, <span class="va">bill_length</span>, <span class="va">bill_depth</span>, <span class="va">flipper_length</span><span class="op">)</span></code></pre></div>
<p>For the following, we will use:</p>
<p><span class="math display">\[\alpha_{\text{entry}} = 0.05, \quad \alpha_{\text{exit}} = 0.05\]</span></p>
<div id="building-the-base-model" class="section level3" number="4.4.1">
<h3>
<span class="header-section-number">4.4.1</span> Building the base model<a class="anchor" aria-label="anchor" href="#building-the-base-model"><i class="fas fa-link"></i></a>
</h3>
<p>We are interested in performing stepwise selection using <code>body_mass</code> as the response. As recommended
in the lecture notes, we commence the model building process by including the predictor that is most
correlated to <code>body_mass</code>.</p>
<div class="sourceCode" id="cb248"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">adeliebiscoe</span><span class="op">)</span></code></pre></div>
<pre><code>##                body_mass bill_length bill_depth flipper_length
## body_mass      1.0000000   0.6477493  0.6516595      0.5261972
## bill_length    0.6477493   1.0000000  0.4681935      0.3366548
## bill_depth     0.6516595   0.4681935  1.0000000      0.2727782
## flipper_length 0.5261972   0.3366548  0.2727782      1.0000000</code></pre>
<p><code>bill_depth</code> is the most correlated with <code>body_mass</code> (remember to look at the absolute value of the
correlation).</p>
<div class="sourceCode" id="cb250"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">step1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass</span> <span class="op">~</span> <span class="va">bill_depth</span>, data<span class="op">=</span><span class="va">adeliebiscoe</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">step1</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = body_mass ~ bill_depth, data = adeliebiscoe)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -846.03 -227.10  -27.46  275.68  897.03 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1201.76     883.92  -1.360    0.181    
## bill_depth    267.35      48.02   5.568 1.66e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 374.3 on 42 degrees of freedom
## Multiple R-squared:  0.4247, Adjusted R-squared:  0.411 
## F-statistic:    31 on 1 and 42 DF,  p-value: 1.658e-06</code></pre>
<p>From the summary output, the <span class="math inline">\(t\)</span>-test of <code>bill_depth</code> is significant so we can continue considering
predictors to add to the model.</p>
</div>
<div id="adding-a-predictor-round-1" class="section level3" number="4.4.2">
<h3>
<span class="header-section-number">4.4.2</span> Adding a predictor, round 1<a class="anchor" aria-label="anchor" href="#adding-a-predictor-round-1"><i class="fas fa-link"></i></a>
</h3>
<p>Note that we can perform the partial <span class="math inline">\(F\)</span>-tests of single predictor additions using the usual method
of building the candidate model and then calling <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> on the reduced and full models.</p>
<div class="sourceCode" id="cb252"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">step2a</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass</span> <span class="op">~</span> <span class="va">bill_depth</span> <span class="op">+</span> <span class="va">bill_length</span>, data<span class="op">=</span><span class="va">adeliebiscoe</span><span class="op">)</span>
<span class="va">step2b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass</span> <span class="op">~</span> <span class="va">bill_depth</span> <span class="op">+</span> <span class="va">flipper_length</span>, data<span class="op">=</span><span class="va">adeliebiscoe</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">step1</span>, <span class="va">step2a</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: body_mass ~ bill_depth
## Model 2: body_mass ~ bill_depth + bill_length
##   Res.Df     RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1     42 5885163                                  
## 2     41 4347044  1   1538118 14.507 0.0004594 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<div class="sourceCode" id="cb254"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">step1</span>, <span class="va">step2b</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: body_mass ~ bill_depth
## Model 2: body_mass ~ bill_depth + flipper_length
##   Res.Df     RSS Df Sum of Sq      F   Pr(&gt;F)   
## 1     42 5885163                                
## 2     41 4543427  1   1341736 12.108 0.001205 **
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>This can become a lot of work at each step and can become tedious if there are many predictors to
consider at each step. Instead, we can perform the partial <span class="math inline">\(F\)</span>-tests of single predictor additions
using the <code><a href="https://rdrr.io/r/stats/add1.html">add1()</a></code> function.</p>
<div class="sourceCode" id="cb256"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">add1</a></span><span class="op">(</span><span class="va">step1</span>, <span class="op">~</span> <span class="va">.</span> <span class="op">+</span> <span class="va">bill_length</span> <span class="op">+</span> <span class="va">flipper_length</span>, test<span class="op">=</span><span class="st">"F"</span><span class="op">)</span></code></pre></div>
<pre><code>## Single term additions
## 
## Model:
## body_mass ~ bill_depth
##                Df Sum of Sq     RSS    AIC F value    Pr(&gt;F)    
## &lt;none&gt;                      5885163 523.37                      
## bill_length     1   1538118 4347044 512.04  14.507 0.0004594 ***
## flipper_length  1   1341736 4543427 513.98  12.108 0.0012047 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>The first argument to <code><a href="https://rdrr.io/r/stats/add1.html">add1()</a></code> is the base model which we are considering adding predictors to. The
second argument is the scope, where we list all predictors (using formula syntax) that are eligible
to be added to the main model. Notice that the results of the partial <span class="math inline">\(F\)</span>-tests are identical to
the previous results when we had constructed the models individually (<code>step2a</code> and <code>step2b</code>).</p>
<p>The predictor that gets added to our model is the one associated to the highest <span class="math inline">\(F\)</span>-value. Since
each of these <span class="math inline">\(F\)</span>-values have the same numerator and denominator degrees of freedom, this is also
equivalent to adding the predictor that has the smallest <span class="math inline">\(p\)</span>-value associated to its partial
<span class="math inline">\(F\)</span>-test (so long as it is less than <span class="math inline">\(\alpha_{\text{entry}}\)</span>). Since the <span class="math inline">\(F\)</span>-test of adding
<code>bill_length</code> to the base model results in the smallest <span class="math inline">\(p\)</span>-value that is less than
<span class="math inline">\(\alpha_{\text{entry}}\)</span>, <code>bill_length</code> is added to the base model.</p>
<div class="sourceCode" id="cb258"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">step2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">step1</span>, <span class="va">.</span> <span class="op">~</span> <span class="va">.</span> <span class="op">+</span> <span class="va">bill_length</span><span class="op">)</span></code></pre></div>
</div>
<div id="dropping-a-predictor-round-1" class="section level3" number="4.4.3">
<h3>
<span class="header-section-number">4.4.3</span> Dropping a predictor, round 1<a class="anchor" aria-label="anchor" href="#dropping-a-predictor-round-1"><i class="fas fa-link"></i></a>
</h3>
<p>Now we check whether there are any predictors that can be dropped. As before, we can construct
multiple models that differ by single term deletions and perform the partial <span class="math inline">\(F\)</span>-tests by
calling <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> on the reduced and full models. We can also use the equivalent of <code><a href="https://rdrr.io/r/stats/add1.html">add1()</a></code> for
single term deletions, which is <code><a href="https://rdrr.io/r/stats/add1.html">drop1()</a></code>.</p>
<div class="sourceCode" id="cb259"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">drop1</a></span><span class="op">(</span><span class="va">step2</span>, <span class="op">~</span> <span class="va">.</span>, test<span class="op">=</span><span class="st">"F"</span><span class="op">)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## body_mass ~ bill_depth + bill_length
##             Df Sum of Sq     RSS    AIC F value    Pr(&gt;F)    
## &lt;none&gt;                   4347044 512.04                      
## bill_depth   1   1590092 5937136 523.75  14.997 0.0003796 ***
## bill_length  1   1538118 5885163 523.37  14.507 0.0004594 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>The first argument to <code><a href="https://rdrr.io/r/stats/add1.html">drop1()</a></code> is the model from which we are considering dropping predictors from.
The second argument is the scope (similar to <code><a href="https://rdrr.io/r/stats/add1.html">add1()</a></code>), where we list all predictors (using formula
syntax) that are eligible to be dropped from the main model. Here, all predictors currently in the
model under consideration are eligible to be dropped.</p>
<p>Recall that the hypotheses associated to dropping a single predictor are:</p>
<p><span class="math display">\[H_{0}: \beta_{1} = 0, \quad H_{A}: \beta_{1} \neq 0\]</span>
<span class="math display">\[H_{0}: \beta_{2} = 0, \quad H_{A}: \beta_{2} \neq 0\]</span></p>
<p>For a predictor to be dropped from the model, we need to fail to reject the null hypothesis. So we
are looking for small <span class="math inline">\(F\)</span>-values, or equivalently, large <span class="math inline">\(p\)</span>-values that are greater than
<span class="math inline">\(\alpha_{\text{exit}}\)</span>. Since we do not have any here, we do not drop any of the predictors from the
current model.</p>
</div>
<div id="adding-a-predictor-round-2" class="section level3" number="4.4.4">
<h3>
<span class="header-section-number">4.4.4</span> Adding a predictor, round 2<a class="anchor" aria-label="anchor" href="#adding-a-predictor-round-2"><i class="fas fa-link"></i></a>
</h3>
<p>At this stage, we only have one more variable left in our data set that can be added to the model.</p>
<div class="sourceCode" id="cb261"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">add1</a></span><span class="op">(</span><span class="va">step2</span>, <span class="op">~</span> <span class="va">.</span> <span class="op">+</span> <span class="va">flipper_length</span>, test<span class="op">=</span><span class="st">"F"</span><span class="op">)</span></code></pre></div>
<pre><code>## Single term additions
## 
## Model:
## body_mass ~ bill_depth + bill_length
##                Df Sum of Sq     RSS    AIC F value   Pr(&gt;F)   
## &lt;none&gt;                      4347044 512.04                    
## flipper_length  1    775322 3571722 505.39  8.6829 0.005336 **
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>Since the <span class="math inline">\(p\)</span>-value for this <span class="math inline">\(F\)</span>-test is less than <span class="math inline">\(\alpha_{\text{entry}}\)</span>, we add <code>flipper_length</code>
into the main model.</p>
<div class="sourceCode" id="cb263"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">step3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">step2</span>, <span class="va">.</span> <span class="op">~</span> <span class="va">.</span> <span class="op">+</span> <span class="va">flipper_length</span><span class="op">)</span></code></pre></div>
</div>
<div id="dropping-a-predictor-round-2" class="section level3" number="4.4.5">
<h3>
<span class="header-section-number">4.4.5</span> Dropping a predictor, round 2<a class="anchor" aria-label="anchor" href="#dropping-a-predictor-round-2"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb264"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">drop1</a></span><span class="op">(</span><span class="va">step3</span>, <span class="op">~</span> <span class="va">.</span>, test<span class="op">=</span><span class="st">"F"</span><span class="op">)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## body_mass ~ bill_depth + bill_length + flipper_length
##                Df Sum of Sq     RSS    AIC F value    Pr(&gt;F)    
## &lt;none&gt;                      3571722 505.39                      
## bill_depth      1   1270094 4841816 516.78 14.2239 0.0005257 ***
## bill_length     1    971705 4543427 513.98 10.8822 0.0020456 ** 
## flipper_length  1    775322 4347044 512.04  8.6829 0.0053359 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>As before, predictors that should be considered for dropping are those that have a <span class="math inline">\(p\)</span>-value greater
than <span class="math inline">\(\alpha_{\text{exit}}\)</span>. Since we do not have any, we do not drop any of the predictors in our
model.</p>
</div>
<div id="the-final-model" class="section level3" number="4.4.6">
<h3>
<span class="header-section-number">4.4.6</span> The final model<a class="anchor" aria-label="anchor" href="#the-final-model"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb266"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">step3</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = body_mass ~ bill_depth + bill_length + flipper_length, 
##     data = adeliebiscoe)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -836.50 -186.29   19.01  183.14  486.90 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    -6122.000   1341.697  -4.563 4.71e-05 ***
## bill_depth       165.196     43.802   3.771 0.000526 ***
## bill_length       70.743     21.445   3.299 0.002046 ** 
## flipper_length    21.397      7.262   2.947 0.005336 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 298.8 on 40 degrees of freedom
## Multiple R-squared:  0.6508, Adjusted R-squared:  0.6246 
## F-statistic: 24.85 on 3 and 40 DF,  p-value: 3.048e-09</code></pre>
<p>The final model is:</p>
<p><span class="math display">\[\widehat{Y}_{i} \,=\, -6122.000 \,+\, 165.196X_{1,\,i} + 70.743X_{2,\,i} \,+\, 21.397X_{3,\,i}\]</span></p>
<p>Note that our adjusted R-squared value is 0.6246, which is not terrible, but not great. However,
recall that in the last lab, removing the intercept from the model did result in a jump in the
adjusted R-squared from 0.6246 to 0.9905.</p>
</div>
</div>
<div id="backward-selection" class="section level2" number="4.5">
<h2>
<span class="header-section-number">4.5</span> Backward selection<a class="anchor" aria-label="anchor" href="#backward-selection"><i class="fas fa-link"></i></a>
</h2>
<p>In backward selection, we start with the full model and at each step, consider dropping predictors.
As we had seen for the Adelie Biscoe data, performing the <span class="math inline">\(F\)</span>-test for single term deletions on the
model that contained all predictors, none were eligible for dropping. Therefore, for this example,
let us consider another data set — the
<a href="https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-07-13/readme.md">Scooby Doo data set</a>,
which is abundant in variables.</p>
<div class="sourceCode" id="cb268"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scoobydoo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-13/scoobydoo.csv"</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb269"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">scoobydoo</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] "index"                    "series_name"             
##  [3] "network"                  "season"                  
##  [5] "title"                    "imdb"                    
##  [7] "engagement"               "date_aired"              
##  [9] "run_time"                 "format"                  
## [11] "monster_name"             "monster_gender"          
## [13] "monster_type"             "monster_subtype"         
## [15] "monster_species"          "monster_real"            
## [17] "monster_amount"           "caught_fred"             
## [19] "caught_daphnie"           "caught_velma"            
## [21] "caught_shaggy"            "caught_scooby"           
## [23] "captured_fred"            "captured_daphnie"        
## [25] "captured_velma"           "captured_shaggy"         
## [27] "captured_scooby"          "unmask_fred"             
## [29] "unmask_daphnie"           "unmask_velma"            
## [31] "unmask_shaggy"            "unmask_scooby"           
## [33] "snack_fred"               "snack_daphnie"           
## [35] "snack_velma"              "snack_shaggy"            
## [37] "snack_scooby"             "unmask_other"            
## [39] "caught_other"             "caught_not"              
## [41] "trap_work_first"          "setting_terrain"         
## [43] "setting_country_state"    "suspects_amount"         
## [45] "non_suspect"              "arrested"                
## [47] "culprit_name"             "culprit_gender"          
## [49] "culprit_amount"           "motive"                  
## [51] "if_it_wasnt_for"          "and_that"                
## [53] "door_gag"                 "number_of_snacks"        
## [55] "split_up"                 "another_mystery"         
## [57] "set_a_trap"               "jeepers"                 
## [59] "jinkies"                  "my_glasses"              
## [61] "just_about_wrapped_up"    "zoinks"                  
## [63] "groovy"                   "scooby_doo_where_are_you"
## [65] "rooby_rooby_roo"          "batman"                  
## [67] "scooby_dum"               "scrappy_doo"             
## [69] "hex_girls"                "blue_falcon"             
## [71] "fred_va"                  "daphnie_va"              
## [73] "velma_va"                 "shaggy_va"               
## [75] "scooby_va"</code></pre>
<div id="data-prep" class="section level3" number="4.5.1">
<h3>
<span class="header-section-number">4.5.1</span> Data prep<a class="anchor" aria-label="anchor" href="#data-prep"><i class="fas fa-link"></i></a>
</h3>
<p>For this example, we will only keep a subset of the variables for the sake of brevity. In addition,
some of the variables that should be of type numeric were read in as strings due to the presence
of the string <code>"NULL"</code> (note that the string <code>"NULL"</code> is not the same as <code>NULL</code>, which is also not
the same as <code>NA</code>). For example:</p>
<div class="sourceCode" id="cb271"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scoobydoo</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">jinkies</span><span class="op">)</span></code></pre></div>
<pre class="fansi fansi-output"><code>## <span style="color: #555555;"># A tibble: 14 x 2</span><span>
##    jinkies     n
##    </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>   </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span>
## </span><span style="color: #555555;"> 1</span><span> 0         176
## </span><span style="color: #555555;"> 2</span><span> 1          92
## </span><span style="color: #555555;"> 3</span><span> 10          1
## </span><span style="color: #555555;"> 4</span><span> 11          1
## </span><span style="color: #555555;"> 5</span><span> 13          1
## </span><span style="color: #555555;"> 6</span><span> 2          53
## </span><span style="color: #555555;"> 7</span><span> 3          27
## </span><span style="color: #555555;"> 8</span><span> 4          11
## </span><span style="color: #555555;"> 9</span><span> 5           5
## </span><span style="color: #555555;">10</span><span> 6          10
## </span><span style="color: #555555;">11</span><span> 7           4
## </span><span style="color: #555555;">12</span><span> 8           3
## </span><span style="color: #555555;">13</span><span> 9           1
## </span><span style="color: #555555;">14</span><span> NULL      218
</span></code></pre>
<p>Therefore, we want to remove all episodes that contain <code>"NULL"</code> values in selected columns and
coerce the remaining values to numeric.</p>
<div class="sourceCode" id="cb272"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scoobydoo</span> <span class="op">&lt;-</span> <span class="va">scoobydoo</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span>
    <span class="va">imdb</span>, <span class="va">engagement</span>, <span class="va">run_time</span>, <span class="va">monster_amount</span>, <span class="va">suspects_amount</span>, <span class="va">culprit_amount</span>,
    <span class="va">jeepers</span>, <span class="va">jinkies</span>, <span class="va">my_glasses</span>, <span class="va">zoinks</span>
  <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.character</span><span class="op">)</span>, <span class="op">~</span> <span class="va">.</span> <span class="op">!=</span> <span class="st">"NULL"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.character</span><span class="op">)</span>, <span class="va">as.numeric</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>In the line containing <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>, we are filtering over all character-type columns to only retain
episodes that do not contain any <code>"NULL"</code> values. Specifying the filtering condition this way
allows us to do less typing. Otherwise, we would need to type out all the variables of interest:</p>
<div class="sourceCode" id="cb273"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">imdb</span> <span class="op">!=</span> <span class="st">"NULL"</span>, <span class="va">jeepers</span> <span class="op">!=</span> <span class="st">"NULL"</span>, <span class="va">jinkies</span> <span class="op">!=</span> <span class="st">"NULL"</span>, <span class="va">etc.</span><span class="op">)</span></code></pre></div>
<p>Note that the portion <code>~ . != "NULL"</code> is a lambda function / anonymous function, not a mathematical
formula, and is the short-hand equivalent to:</p>
<div class="sourceCode" id="cb274"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">{</span>
  <span class="va">x</span> <span class="op">!=</span> <span class="st">"NULL"</span>
<span class="op">}</span></code></pre></div>
<p>Previewing our data:</p>
<div class="sourceCode" id="cb275"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scoobydoo</span></code></pre></div>
<pre class="fansi fansi-output"><code>## <span style="color: #555555;"># A tibble: 369 x 10</span><span>
##     imdb engagement run_time monster_amount suspects_amount culprit_amount jeepers jinkies my_glasses zoinks
##    </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>      </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>    </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>          </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>           </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>          </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>   </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>   </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>      </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>  </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>
## </span><span style="color: #555555;"> 1</span><span>   8.1        556       21              1               2              1       0       0          1      1
## </span><span style="color: #555555;"> 2</span><span>   8.1        479       22              1               2              1       0       0          0      3
## </span><span style="color: #555555;"> 3</span><span>   8          455       21              1               0              1       0       0          0      1
## </span><span style="color: #555555;"> 4</span><span>   7.8        426       21              1               2              1       0       0          0      2
## </span><span style="color: #555555;"> 5</span><span>   7.5        391       21              1               1              1       0       0          1      0
## </span><span style="color: #555555;"> 6</span><span>   8.4        384       21              1               2              1       1       0          0      2
## </span><span style="color: #555555;"> 7</span><span>   7.6        358       21              1               1              1       0       0          0      1
## </span><span style="color: #555555;"> 8</span><span>   8.2        358       21              1               2              1       0       0          1      0
## </span><span style="color: #555555;"> 9</span><span>   8.1        371       21              1               1              1       0       0          0      0
## </span><span style="color: #555555;">10</span><span>   8          346       21              1               1              1       0       0          0      0
## </span><span style="color: #555555;"># ... with 359 more rows</span><span>
</span></code></pre>
<p>Now we are ready to start building models. We are interested in creating a model that predicts
the IMDB rating. As we are performing backward selection, we start with the model containing all
predictors. For the following example, we will use <span class="math inline">\(\alpha_{\text{exit}} = 0.05\)</span>.</p>
<div class="sourceCode" id="cb276"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">back1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">imdb</span> <span class="op">~</span> <span class="va">.</span>, data<span class="op">=</span><span class="va">scoobydoo</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">back1</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = imdb ~ ., data = scoobydoo)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.84731 -0.30812 -0.02295  0.33015  2.48946 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      8.221e+00  7.074e-02 116.212  &lt; 2e-16 ***
## engagement      -6.610e-06  5.797e-06  -1.140 0.254938    
## run_time        -1.040e-02  2.293e-03  -4.536 7.84e-06 ***
## monster_amount  -4.792e-02  2.054e-02  -2.333 0.020207 *  
## suspects_amount -6.519e-02  1.489e-02  -4.377 1.58e-05 ***
## culprit_amount   1.304e-02  2.813e-02   0.464 0.643254    
## jeepers         -2.581e-02  2.384e-02  -1.083 0.279719    
## jinkies         -5.536e-02  1.573e-02  -3.519 0.000488 ***
## my_glasses      -1.156e-01  9.429e-02  -1.226 0.221045    
## zoinks           8.496e-03  1.167e-02   0.728 0.467106    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.5547 on 359 degrees of freedom
## Multiple R-squared:  0.3503, Adjusted R-squared:  0.334 
## F-statistic: 21.51 on 9 and 359 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="dropping-a-predictor-round-1-1" class="section level3" number="4.5.2">
<h3>
<span class="header-section-number">4.5.2</span> Dropping a predictor, round 1<a class="anchor" aria-label="anchor" href="#dropping-a-predictor-round-1-1"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb278"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">drop1</a></span><span class="op">(</span><span class="va">back1</span>, <span class="op">~</span> <span class="va">.</span>, test<span class="op">=</span><span class="st">"F"</span><span class="op">)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## imdb ~ engagement + run_time + monster_amount + suspects_amount + 
##     culprit_amount + jeepers + jinkies + my_glasses + zoinks
##                 Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
## &lt;none&gt;                       110.48 -425.00                      
## engagement       1    0.4001 110.88 -425.66  1.3002 0.2549380    
## run_time         1    6.3308 116.81 -406.43 20.5713 7.843e-06 ***
## monster_amount   1    1.6748 112.16 -421.44  5.4422 0.0202074 *  
## suspects_amount  1    5.8966 116.38 -407.81 19.1605 1.578e-05 ***
## culprit_amount   1    0.0661 110.55 -426.77  0.2149 0.6432544    
## jeepers          1    0.3607 110.84 -425.79  1.1720 0.2797190    
## jinkies          1    3.8118 114.29 -414.48 12.3861 0.0004882 ***
## my_glasses       1    0.4625 110.94 -425.45  1.5028 0.2210448    
## zoinks           1    0.1631 110.64 -426.45  0.5299 0.4671058    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>Remember that when we are dropping predictors, in the related hypothesis test, we want to fail to
reject the null hypothesis. Therefore we are looking for <span class="math inline">\(p\)</span>-values that are greater than
<span class="math inline">\(\alpha_{\text{exit}} = 0.05\)</span>. From the output above, there are many predictors that are eligible to
be dropped. Therefore, we select the predictor corresponding to the largest <span class="math inline">\(p\)</span>-value greater than
<span class="math inline">\(\alpha_{\text{exit}} = 0.05\)</span>. This is <code>culprit_amount</code> with a <span class="math inline">\(p\)</span>-value of 0.643.</p>
<div class="sourceCode" id="cb280"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">back2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">back1</span>, <span class="va">.</span> <span class="op">~</span> <span class="va">.</span> <span class="op">-</span> <span class="va">culprit_amount</span><span class="op">)</span></code></pre></div>
</div>
<div id="dropping-a-predictor-round-2-1" class="section level3" number="4.5.3">
<h3>
<span class="header-section-number">4.5.3</span> Dropping a predictor, round 2<a class="anchor" aria-label="anchor" href="#dropping-a-predictor-round-2-1"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb281"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">drop1</a></span><span class="op">(</span><span class="va">back2</span>, <span class="op">~</span> <span class="va">.</span>, test<span class="op">=</span><span class="st">"F"</span><span class="op">)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## imdb ~ engagement + run_time + monster_amount + suspects_amount + 
##     jeepers + jinkies + my_glasses + zoinks
##                 Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
## &lt;none&gt;                       110.55 -426.77                      
## engagement       1    0.4102 110.96 -427.41  1.3359   0.24853    
## run_time         1    6.2755 116.82 -408.40 20.4364 8.377e-06 ***
## monster_amount   1    1.6124 112.16 -423.43  5.2509   0.02251 *  
## suspects_amount  1    5.8491 116.40 -409.75 19.0476 1.668e-05 ***
## jeepers          1    0.3504 110.90 -427.61  1.1409   0.28617    
## jinkies          1    3.8516 114.40 -416.14 12.5429   0.00045 ***
## my_glasses       1    0.4734 111.02 -427.20  1.5416   0.21518    
## zoinks           1    0.1479 110.69 -428.28  0.4816   0.48816    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>The variable with the largest <span class="math inline">\(p\)</span>-value greater than <span class="math inline">\(\alpha_{\text{exit}} = 0.05\)</span> is <code>zoinks</code>.</p>
<div class="sourceCode" id="cb283"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">back3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">back2</span>, <span class="va">.</span> <span class="op">~</span> <span class="va">.</span> <span class="op">-</span> <span class="va">zoinks</span><span class="op">)</span></code></pre></div>
</div>
<div id="dropping-a-predictor-round-3" class="section level3" number="4.5.4">
<h3>
<span class="header-section-number">4.5.4</span> Dropping a predictor, round 3<a class="anchor" aria-label="anchor" href="#dropping-a-predictor-round-3"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb284"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">drop1</a></span><span class="op">(</span><span class="va">back3</span>, <span class="op">~</span> <span class="va">.</span>, test<span class="op">=</span><span class="st">"F"</span><span class="op">)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## imdb ~ engagement + run_time + monster_amount + suspects_amount + 
##     jeepers + jinkies + my_glasses
##                 Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
## &lt;none&gt;                       110.69 -428.28                      
## engagement       1    0.3912 111.09 -428.98  1.2758 0.2594306    
## run_time         1    6.2058 116.90 -410.15 20.2383 9.231e-06 ***
## monster_amount   1    1.5627 112.26 -425.11  5.0961 0.0245764 *  
## suspects_amount  1    5.8494 116.55 -411.28 19.0762 1.643e-05 ***
## jeepers          1    0.2204 110.92 -429.55  0.7188 0.3970933    
## jinkies          1    3.7181 114.41 -418.09 12.1255 0.0005584 ***
## my_glasses       1    0.4628 111.16 -428.74  1.5093 0.2200451    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>The variable with the largest <span class="math inline">\(p\)</span>-value greater than <span class="math inline">\(\alpha_{\text{exit}} = 0.05\)</span> is <code>jeepers</code>.</p>
<div class="sourceCode" id="cb286"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">back4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">back3</span>, <span class="va">.</span> <span class="op">~</span> <span class="va">.</span> <span class="op">-</span> <span class="va">jeepers</span><span class="op">)</span></code></pre></div>
</div>
<div id="dropping-a-predictor-round-4" class="section level3" number="4.5.5">
<h3>
<span class="header-section-number">4.5.5</span> Dropping a predictor, round 4<a class="anchor" aria-label="anchor" href="#dropping-a-predictor-round-4"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb287"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">drop1</a></span><span class="op">(</span><span class="va">back4</span>, <span class="op">~</span> <span class="va">.</span>, test<span class="op">=</span><span class="st">"F"</span><span class="op">)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## imdb ~ engagement + run_time + monster_amount + suspects_amount + 
##     jinkies + my_glasses
##                 Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
## &lt;none&gt;                       110.92 -429.55                      
## engagement       1    0.3585 111.27 -430.36  1.1702 0.2800874    
## run_time         1    6.6587 117.57 -410.03 21.7322 4.414e-06 ***
## monster_amount   1    1.5324 112.45 -426.48  5.0015 0.0259342 *  
## suspects_amount  1    5.8929 116.81 -412.45 19.2328 1.519e-05 ***
## jinkies          1    3.7525 114.67 -419.27 12.2471 0.0005241 ***
## my_glasses       1    0.4743 111.39 -429.97  1.5479 0.2142514    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>The variable with the largest <span class="math inline">\(p\)</span>-value greater than <span class="math inline">\(\alpha_{\text{exit}} = 0.05\)</span> is <code>engagement</code>.</p>
<div class="sourceCode" id="cb289"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">back5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">back4</span>, <span class="va">.</span> <span class="op">~</span> <span class="va">.</span> <span class="op">-</span> <span class="va">engagement</span><span class="op">)</span></code></pre></div>
</div>
<div id="dropping-a-predictor-round-5" class="section level3" number="4.5.6">
<h3>
<span class="header-section-number">4.5.6</span> Dropping a predictor, round 5<a class="anchor" aria-label="anchor" href="#dropping-a-predictor-round-5"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb290"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">drop1</a></span><span class="op">(</span><span class="va">back5</span>, <span class="op">~</span> <span class="va">.</span>, test<span class="op">=</span><span class="st">"F"</span><span class="op">)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## imdb ~ run_time + monster_amount + suspects_amount + jinkies + 
##     my_glasses
##                 Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
## &lt;none&gt;                       111.27 -430.36                      
## run_time         1    7.2140 118.49 -409.18 23.5337 1.825e-06 ***
## monster_amount   1    2.3265 113.60 -424.72  7.5896 0.0061662 ** 
## suspects_amount  1    6.0337 117.31 -412.87 19.6833 1.214e-05 ***
## jinkies          1    4.1226 115.40 -418.93 13.4489 0.0002818 ***
## my_glasses       1    0.8231 112.10 -429.64  2.6852 0.1021524    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>The variable with the largest <span class="math inline">\(p\)</span>-value greater than <span class="math inline">\(\alpha_{\text{exit}} = 0.05\)</span> is <code>my_glasses</code>.</p>
<div class="sourceCode" id="cb292"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">back6</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">back5</span>, <span class="va">.</span> <span class="op">~</span> <span class="va">.</span> <span class="op">-</span> <span class="va">my_glasses</span><span class="op">)</span></code></pre></div>
</div>
<div id="dropping-a-predictor-round-6" class="section level3" number="4.5.7">
<h3>
<span class="header-section-number">4.5.7</span> Dropping a predictor, round 6<a class="anchor" aria-label="anchor" href="#dropping-a-predictor-round-6"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb293"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">drop1</a></span><span class="op">(</span><span class="va">back6</span>, <span class="op">~</span> <span class="va">.</span>, test<span class="op">=</span><span class="st">"F"</span><span class="op">)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## imdb ~ run_time + monster_amount + suspects_amount + jinkies
##                 Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
## &lt;none&gt;                       112.10 -429.64                      
## run_time         1    8.2939 120.39 -405.30 26.9316  3.51e-07 ***
## monster_amount   1    2.4078 114.50 -423.79  7.8187 0.0054452 ** 
## suspects_amount  1    5.9769 118.07 -412.47 19.4080  1.39e-05 ***
## jinkies          1    4.3332 116.43 -417.64 14.0708 0.0002048 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>The remaining single term deletions have <span class="math inline">\(p\)</span>-values that are less than
<span class="math inline">\(\alpha_{\text{exit}} = 0.05\)</span>. Therefore, we stop here.</p>
</div>
<div id="the-final-model-1" class="section level3" number="4.5.8">
<h3>
<span class="header-section-number">4.5.8</span> The final model<a class="anchor" aria-label="anchor" href="#the-final-model-1"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb295"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">back6</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = imdb ~ run_time + monster_amount + suspects_amount + 
##     jinkies, data = scoobydoo)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.89720 -0.30625 -0.03038  0.33928  2.42649 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      8.264472   0.062373 132.501  &lt; 2e-16 ***
## run_time        -0.011483   0.002213  -5.190 3.51e-07 ***
## monster_amount  -0.052395   0.018738  -2.796 0.005445 ** 
## suspects_amount -0.064694   0.014685  -4.405 1.39e-05 ***
## jinkies         -0.057869   0.015427  -3.751 0.000205 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.5549 on 364 degrees of freedom
## Multiple R-squared:  0.3408, Adjusted R-squared:  0.3336 
## F-statistic: 47.04 on 4 and 364 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The final model is:</p>
<p><span class="math display">\[\widehat{Y}_{i} \,=\, 8.2645 \,-\, 0.0114X_{1,\,i} \,-\, 0.0524X_{2,\,i} - 0.0647X_{3,\,i} - 0.0579X_{4,\,i}\]</span></p>
<p>Interestingly, this says that the number of jinkies in an episode has a (small) negative impact on
the IMDB rating 😂!</p>
<p>While all the remaining predictors in our model are significant, we have a very poor adjusted
R-squared value of 0.3336. This means that we have only explained 33.36% of the variation in
IMDB ratings by using these predictors. In fact, our original model with all the predictors had an
adjusted R-squared value of 0.3340. As such, the final model still has room for improvement
(though do keep in mind that only a small subset of variables were included in this example for the
sake of brevity).</p>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="lab-5-october-13.html"><span class="header-section-number">3</span> Lab 5 — October 13</a></div>
<div class="next"><a href="lab-9-december-1.html"><span class="header-section-number">5</span> Lab 9 — December 1</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#lab-7-november-10"><span class="header-section-number">4</span> Lab 7 — November 10</a></li>
<li><a class="nav-link" href="#packages-1"><span class="header-section-number">4.1</span> Packages</a></li>
<li>
<a class="nav-link" href="#weighted-linear-regression-via-lm"><span class="header-section-number">4.2</span> Weighted linear regression (via lm)</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#problem-i"><span class="header-section-number">4.2.1</span> Problem (i)</a></li>
<li><a class="nav-link" href="#solution"><span class="header-section-number">4.2.2</span> Solution</a></li>
<li><a class="nav-link" href="#problem-ii"><span class="header-section-number">4.2.3</span> Problem (ii)</a></li>
<li><a class="nav-link" href="#solution-1"><span class="header-section-number">4.2.4</span> Solution</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#all-possible-models"><span class="header-section-number">4.3</span> All possible models</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#a-custom-tidy-function"><span class="header-section-number">4.3.1</span> A custom tidy function</a></li>
<li><a class="nav-link" href="#getting-the-results"><span class="header-section-number">4.3.2</span> Getting the results</a></li>
<li><a class="nav-link" href="#obtaining-the-values-for-the-intercept-only-model"><span class="header-section-number">4.3.3</span> Obtaining the values for the intercept-only model</a></li>
<li><a class="nav-link" href="#plotting-the-results"><span class="header-section-number">4.3.4</span> Plotting the results</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#stepwise-selection"><span class="header-section-number">4.4</span> Stepwise selection</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#building-the-base-model"><span class="header-section-number">4.4.1</span> Building the base model</a></li>
<li><a class="nav-link" href="#adding-a-predictor-round-1"><span class="header-section-number">4.4.2</span> Adding a predictor, round 1</a></li>
<li><a class="nav-link" href="#dropping-a-predictor-round-1"><span class="header-section-number">4.4.3</span> Dropping a predictor, round 1</a></li>
<li><a class="nav-link" href="#adding-a-predictor-round-2"><span class="header-section-number">4.4.4</span> Adding a predictor, round 2</a></li>
<li><a class="nav-link" href="#dropping-a-predictor-round-2"><span class="header-section-number">4.4.5</span> Dropping a predictor, round 2</a></li>
<li><a class="nav-link" href="#the-final-model"><span class="header-section-number">4.4.6</span> The final model</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#backward-selection"><span class="header-section-number">4.5</span> Backward selection</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#data-prep"><span class="header-section-number">4.5.1</span> Data prep</a></li>
<li><a class="nav-link" href="#dropping-a-predictor-round-1-1"><span class="header-section-number">4.5.2</span> Dropping a predictor, round 1</a></li>
<li><a class="nav-link" href="#dropping-a-predictor-round-2-1"><span class="header-section-number">4.5.3</span> Dropping a predictor, round 2</a></li>
<li><a class="nav-link" href="#dropping-a-predictor-round-3"><span class="header-section-number">4.5.4</span> Dropping a predictor, round 3</a></li>
<li><a class="nav-link" href="#dropping-a-predictor-round-4"><span class="header-section-number">4.5.5</span> Dropping a predictor, round 4</a></li>
<li><a class="nav-link" href="#dropping-a-predictor-round-5"><span class="header-section-number">4.5.6</span> Dropping a predictor, round 5</a></li>
<li><a class="nav-link" href="#dropping-a-predictor-round-6"><span class="header-section-number">4.5.7</span> Dropping a predictor, round 6</a></li>
<li><a class="nav-link" href="#the-final-model-1"><span class="header-section-number">4.5.8</span> The final model</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/adamoshen/3553f21/blob/main/04.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/adamoshen/3553f21/edit/main/04.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Stat 3553: Regression Modelling</strong>: Fall 2021" was written by Adam Shen. It was last built on December 01, 2021.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
